# Generated by Django 5.1 on 2024-09-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.continent')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.AddField(
            model_name='attraction',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.country'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.country'),
        ),
    ]
