# Generated by Django 5.1 on 2024-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_accommodation_attraction_continent_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
