# Generated by Django 5.1 on 2024-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('continent', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('culturalinsights', models.TextField()),
                ('accomodations', models.TextField()),
                ('accimgs', models.ImageField(upload_to='')),
                ('dining', models.TextField()),
                ('diningimgs', models.ImageField(upload_to='')),
            ],
        ),
    ]
