# Generated by Django 5.1 on 2024-08-31 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='description',
            new_name='country_discription',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='accimgs',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='accomodations',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='culturalinsights',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='dining',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='diningimgs',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DestinationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('images', models.JSONField()),
                ('cultural_insights', models.TextField()),
                ('popular_accommodations', models.TextField()),
                ('accommodation_images', models.JSONField()),
                ('dining_options', models.TextField()),
                ('dining_images', models.JSONField()),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.destination')),
            ],
        ),
    ]
