# Generated by Django 5.1 on 2024-08-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_description_destination_country_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationdetails',
            name='accommodation_images',
        ),
        migrations.RemoveField(
            model_name='destinationdetails',
            name='dining_images',
        ),
        migrations.RemoveField(
            model_name='destinationdetails',
            name='dining_options',
        ),
        migrations.RemoveField(
            model_name='destinationdetails',
            name='popular_accommodations',
        ),
        migrations.AlterField(
            model_name='destinationdetails',
            name='images',
            field=models.ImageField(upload_to='destination_images/'),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='accommodation_images/')),
                ('destination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='home.destinationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DiningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='dining_images/')),
                ('destination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_options', to='home.destinationdetails')),
            ],
        ),
    ]
