# Generated by Django 5.1 on 2024-09-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_destinationdetails_accommodation_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('historical', 'Historical Places'), ('food', 'Popular Foods'), ('restaurant', 'Restaurants'), ('national_park', 'National Parks'), ('popular_places', 'Popular Places'), ('festival', 'Local Festivals')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='attraction_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('alt_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='destinationdetails',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='diningoption',
            name='destination_details',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='country_discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='attractions/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='home.destination')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.attractioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='slideshow_images',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='home.slideshowimage'),
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='DestinationDetails',
        ),
        migrations.DeleteModel(
            name='DiningOption',
        ),
    ]
