# Generated by Django 5.1 on 2024-09-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_attractioncategory_slideshowimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='slideshow_images',
        ),
        migrations.AddField(
            model_name='destination',
            name='images',
            field=models.ImageField(default='default_image.jpg', upload_to='destination_images'),
        ),
        migrations.DeleteModel(
            name='SlideshowImage',
        ),
    ]
