# Generated by Django 5.1 on 2024-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_destination_slideshow_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('alt_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='images',
        ),
        migrations.AddField(
            model_name='destination',
            name='slideshow_images',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='home.slideshowimage'),
        ),
    ]
