# Generated by Django 5.1 on 2024-09-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_slideshowimage_remove_destination_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(choices=[('historical', 'Historical Places'), ('food', 'Popular Foods'), ('restaurant', 'Restaurants'), ('national_park', 'National Parks'), ('popular_places', 'Popular Places'), ('festival', 'Local Festivals')], max_length=50),
        ),
        migrations.AddField(
            model_name='attraction',
            name='category_description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.DeleteModel(
            name='AttractionCategory',
        ),
    ]
