# Generated by Django 5.1 on 2024-09-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_attraction_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='category_headings',
        ),
    ]
