# Generated by Django 5.1 on 2024-09-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_attraction_category_headings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='category_description',
        ),
    ]
