# Generated by Django 5.1 on 2024-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_attraction_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(choices=[('Historical Places', 'Harmony between Tradition and Modernity'), ('Foods & Restaurants ', 'Gourmet Travel'), ('Nature', 'Nature and Its Healing Power'), ('Activities', 'Travel Activities'), ('Popular places', 'Popular places (attractions)'), ('Local festivals', 'Local Festivals')], max_length=50),
        ),
    ]
