# Generated by Django 5.1 on 2024-10-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_audiomodel_place_remove_destination_slideshow_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
