# Generated by Django 5.1 on 2024-10-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_destination_remove_hotel_place_remove_review_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='continent_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='continent_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='weather_data',
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Unnamed Destination', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.continent')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.country'),
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
