# Generated by Django 5.1 on 2024-10-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_continent_remove_destination_continent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
