# Generated by Django 5.1 on 2024-10-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_continent_additional_info_country_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='description',
            new_name='destination_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='continent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='continent_name',
            field=models.CharField(default='Unknown Continent', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='country_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='country_name',
            field=models.CharField(default='Unknown Country', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_name',
            field=models.CharField(default='Unknown Destination', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='href',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='home.destination')),
            ],
        ),
        migrations.CreateModel(
            name='BestTimeToVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header_image', models.URLField(blank=True, null=True)),
                ('intropara', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_time_to_visit', to='home.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
