# Generated by Django 5.1 on 2024-10-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_country_continent_remove_destination_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besttimetovisit',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='BestTimeToVisit',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
