# Generated by Django 5.1 on 2024-10-22 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_destination_besttimetovisit_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Continent', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='besttimetovisit',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='continent_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='continent_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country_name',
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Country', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='home.continent')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='home.country'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Region', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='home.country')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='home.region'),
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='BestTimeToVisit',
        ),
    ]
