# Generated by Django 5.1 on 2024-10-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_continent_remove_besttimetovisit_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        
        # migrations.AlterField(
        #     model_name='continent',
        #     name='name',
        #     field=models.CharField(max_length=255, unique=True),
        # ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='home.country'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
