# Generated by Django 5.1 on 2024-10-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_country_continent_remove_destination_region_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='destination',
        #     name='continent',
        # ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='destination',
            name='continent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='continent_name',
            field=models.CharField(default='Unknown Continent', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='country_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='country_name',
            field=models.CharField(default='Unknown Country', max_length=255),
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
